routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sms/{l}/{m}', 'FrontController@SendSMSCode');

Route::get('/test/{l}/{m}', 'FrontController@test');

Route::get('/landing', function () {
    return view('frontend.landing.index');
});

Route::get('/', 'FrontController@index')->name('home');
Route::get('/login', 'FrontController@get_login')->name('login');
Route::post('/login', 'FrontController@login')->name('post_login');
Route::get('/about', 'FrontController@about')->name('about');
Route::get('/services', 'FrontController@services')->name('service');
Route::get('/captain', 'FrontController@captain')->name('captain');
Route::get('/customer', 'FrontController@customer')->name('customer');
Route::get('/tracking', 'FrontController@tracking')->name('tracking');
Route::get('/register', 'FrontController@get_register')->name('register');
Route::post('/register', 'FrontController@register')->name('post_register');
Route::get('/contact', 'FrontController@contact')->name('contact');
Route::post('/contact', 'FrontController@contact_post')->name('contact_post');
Route::get('/terms', 'FrontController@terms')->name('terms');
Route::get('/forgotpassword', 'FrontController@get_forgotpassword')->name('forgotpassword');
Route::post('/forgotpassword', 'FrontController@forgotpassword')->name('forgotPassword');
Route::get('/active_account/{k}', 'FrontController@get_active_account')->name('active_account');
Route::post('/active_account', 'FrontController@active_account')->name('post_active_account');
Route::post('/forgotpasswordcode', 'FrontController@forgotpasswordcode')->name('forgotpasswordcode');
Route::post('/send_active_code', 'FrontController@send_active_code')->name('send_active_code');
Route::post('/resetpassword', 'FrontController@resetpassword')->name('resetpassword');
Route::post('/tracking', 'FrontController@search_tracking')->name('search_tracking');

Route::group(['prefix' => '/customer/account', 'as' => 'profile.', 'middleware' => 'customer'], function () {
    Route::get('/', 'FrontController@dashboard')->name('dashboard');
    Route::get('orders', 'FrontController@orders')->name('orders');
    Route::get('orders/{id}', 'FrontController@orderview')->name('orderview');
    Route::get('orders/{id}/edit', 'FrontController@order_edit_without_lang')->name('order_edit');
    Route::put('orders/{id}', 'FrontController@order_update')->name('order_update');
    Route::get('invoices/', 'FrontController@indexprofilewebsite');

    Route::get("reports/daily_report", "FrontController@profile_daily_report");
    Route::post("reports/daily_report", "Backend\ReportController@profile_daily_report");
    Route::post("orders/add_order_comment", "FrontController@addOrderComment");

    Route::get("invoices", "FrontController@indexInvoice")->name('invoices.index');
    Route::get("invoices/{id}", "FrontController@showInvoice")->name('invoices.show');
    Route::get("print/invoices/{id}", "FrontController@printInvoice");

    Route::get("refund_collections", "FrontController@indexRefund")->name('refund_collections.index');
    Route::any("print_refund", "Backend\ReportController@print_refund")->name("orders.print_refund");
    Route::any("refund_excel", "Backend\ReportController@refund_excel")->name("orders.refund_excel");

    Route::get('upload-excel', 'FrontController@getupdate');
    Route::post('upload-excel', 'FrontController@upload');
    Route::get('process-sheet/{id}', 'FrontController@process');
    Route::post("handle_sheet", "FrontController@handle_sheet");
    Route::post("export_sheet", "FrontController@export_sheet");
    Route::get('order-form', 'FrontController@order_form');
    Route::post('complete_collection/{id}', 'FrontController@complete_collection');
    Route::get('form-collections', 'FrontController@order_form_list')->name('collectionOrders');
    Route::any('form-collections/delete/{id}', 'FrontController@delete_collection')->name('collectionOrders.delete');
    Route::get('wallets', 'FrontController@profilewallet');
    Route::post('cancel_orders', 'FrontController@cancel_orders')->name('cancel_orders');
    Route::post('cancel_orders_request', 'FrontController@cancel_orders_request')->name('cancel_orders_request');
//    Route::get('wallets/', function () {
//        return view('frontend.profile.under_processing');
//    });
    Route::post('tmporders_create', 'FrontController@tmporders_create');
    #tmporders_update_view
    Route::get('tmporders_update_view/{key}', 'FrontController@tmporders_update_view');
    #tmporders_reset_view
    Route::get('tmporders_reset_view/{key}', 'FrontController@tmporders_reset_view');
    Route::get('/recall_if_dropped/{id}', 'FrontController@recall_if_dropped')->name('orders.recall_if_dropped');
    Route::get('logout', 'FrontController@logout');
    Route::get('changepassword', 'FrontController@get_changepassword');
    Route::post('changepassword', 'FrontController@changepassword');
    Route::get('notifications', 'FrontController@notifications');
    Route::get('notifications/delete', 'FrontController@delete_notification')->name('notifications.delete');

    Route::post('edit-profile', 'FrontController@edit_profile')->name('edit-profile');

    Route::get('get_cost/{key}/{receiver}', 'Backend\OrderController@get_cost_sender_receiver');

    Route::any("print_police", "Backend\ReportController@print_police");

    Route::get("customers/details/{id}", "CustomerController@details")->name('customers.details');
    Route::get("customers", "CustomerController@index")->name('customers.index');
    Route::get("customers/create", "CustomerController@create")->name('customers.create');
    Route::post("customers", "CustomerController@store")->name('customers.store');
    Route::get("customers/{id}", "CustomerController@show")->name('customers.show');
    Route::get("customers/{id}/edit", "CustomerController@customer_edit_without_lang")->name('customers.edit');
    Route::put("customers/{id}/update", "CustomerController@update")->name('customers.update');
    Route::delete("customers/{id}", "CustomerController@destroy")->name('customers.destroy');

    Route::get("tasks/cancel_pickup/{key}", "TaskOrderController@cancel_pickup");
    Route::get("tasks/details/{id}", "TaskOrderController@details")->name('tasks.details');
    Route::get("tasks", "TaskOrderController@index")->name('tasks.index');
    Route::get("tasks/create", "TaskOrderController@create")->name('tasks.create');
    Route::post("tasks", "TaskOrderController@store")->name('tasks.store');
    Route::get("tasks/{id}", "TaskOrderController@show")->name('tasks.show');
    Route::get("tasks/{id}/edit", "TaskOrderController@customer_edit_without_lang")->name('tasks.edit');
    Route::put("tasks/{id}/update", "TaskOrderController@update")->name('tasks.update');
    Route::delete("tasks/{id}", "TaskOrderController@destroy")->name('tasks.destroy');
});


Route::group(['prefix' => '{locale}', 'where' => ['locale' => '[a-zA-Z]{2}'], 'middleware' => 'setlocale'], function () {
    Route::get('/', 'FrontController@index')->name('home');
    Route::get('/login', 'FrontController@get_login')->name('login');
    Route::post('/login', 'FrontController@login')->name('post_login');
    Route::get('/about', 'FrontController@about')->name('about');
    Route::get('/services', 'FrontController@services')->name('service');
    Route::get('/captain', 'FrontController@captain')->name('captain');
    Route::get('/customer', 'FrontController@customer')->name('customer');
    Route::get('/tracking', 'FrontController@tracking')->name('tracking');
    Route::get('/register', 'FrontController@get_register')->name('register');
    Route::post('/register', 'FrontController@register')->name('post_register');
    Route::get('/contact', 'FrontController@contact')->name('contact');
    Route::post('/contact', 'FrontController@contact_post')->name('contact_post');
    Route::get('/terms', 'FrontController@terms')->name('terms');
    Route::get('/forgotpassword', 'FrontController@get_forgotpassword')->name('forgotpassword');
    Route::post('/forgotpassword', 'FrontController@forgotpassword')->name('forgotPassword');
    Route::get('/active_account/{k}', 'FrontController@get_active_account')->name('active_account');
    Route::post('/active_account', 'FrontController@active_account')->name('post_active_account');
    Route::post('/forgotpasswordcode', 'FrontController@forgotpasswordcode')->name('forgotpasswordcode');
    Route::post('/send_active_code', 'FrontController@send_active_code')->name('send_active_code');
    Route::post('/resetpassword', 'FrontController@resetpassword')->name('resetpassword');
    Route::post('/tracking', 'FrontController@search_tracking')->name('search_tracking');


    Route::group(['prefix' => '/customer/account', 'as' => 'profile.', 'middleware' => 'customer'], function () {
        Route::get("customers/details/{id}", "CustomerController@details")->name('customers.details');
        Route::get("customers", "CustomerController@index")->name('customers.index');
        Route::get("customers/create", "CustomerController@create")->name('customers.create');
        Route::post("customers", "CustomerController@store")->name('customers.store');
        Route::get("customers/{id}", "CustomerController@show")->name('customers.show');
        Route::get("customers/{id}/edit", "CustomerController@edit")->name('customers.edit');
        Route::put("customers/{id}/update", "CustomerController@update")->name('customers.update');
        Route::delete("customers/{id}", "CustomerController@destroy")->name('customers.destroy');

app/Models/Corporate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Corporate extends Model
{
    public function getActiveSpanAttribute()
    {
        /*
        * is_active = 0 :: Not Active
        * is_active = 1 :: Active
        */
        if ($this->is_active == 1) {
            $value = "<span class='badge badge-pill label-success'>" . __('backend.active') . "</span>";
        } else {
            $value = "<span class='badge badge-pill label-danger'>" . __('backend.not_activated') . "</span>";
        }
        return $value;
    }

    public function getTransferMethodSpanAttribute()
    {

        if ($this->transfer_method == 1) {
            $value = __('backend.bank');
        } elseif ($this->transfer_method == 2) {
            $value = __('backend.mobicash');
        } elseif ($this->transfer_method == 3) {
            $value = __('backend.cash_with_captain');
        } elseif ($this->transfer_method == 4) {
            $value = __('backend.cash_in_office');
        }

        return $value;
    }

    public function getActiveTxtAttribute($value)
    {
        /*
        * is_active = 0 :: Not Active
        * is_active = 1 :: Active
        */
        if ($this->is_active == 0 || $this->is_active != 1) {
            $value = __('backend.active');
        } elseif ($this->is_active == 1) {
            $value = __('backend.not_activated');
        } else {
            $value = "";
        }
        return $value;
    }

    public function getCommercialRecordImageAttribute($value)
    {
        if ($value != "") {
            $value = asset("/api_uploades/client/corporate/commercial/" . $value);
        } else {
            $value = "";
        }
        return $value;
    }


    public function getLogoAttribute($value)
    {
        if ($value != "") {
            if (\File::exists(public_path("/api_uploades/client/corporate/commercial/" . $value))) {
                $value = asset("/api_uploades/client/corporate/commercial/" . $value);
            } else {
                $value = "";
            }
        } else {
            $value = "";
        }

        return $value;
    }

    public function getTypeOfShippingAttribute()
    {
        return $this->shipping_type == 1 ? __('backend.n_shipping') : __('backend.rt_shipping');
    }

    public function getTypeOfAccountAttribute()
    {

        $type = '';

        if ($this->account_type == 1) {
            $type = __('backend.mobile_app');
        } elseif ($this->account_type == 2) {
            $type = __('backend.website');
        } elseif ($this->account_type == 3) {
            $type = __('backend.dashboard');
        }

        return $type;
    }

    public function getIsSomethingWrongAttribute()
    {

        $result = false;

        if (!$this->responsible_id) {
            $result = true;
        }

        foreach ($this->customers as $customer) {
            if (!$customer->store_id) {
                $result = true;
            } elseif (!$customer->government_id) {
                $result = true;
            }
        }

        return $result;
    }

    public function prices()
    {
        return $this->hasMany('App\Models\CorporatePrice');
    }

    public function customers()
    {
        return $this->hasMany('App\Models\Customer');
    }

    public function manager()
    {
        return $this->hasMany('App\Models\Customer')->where('is_manager', 1/**/);
    }

    function orders()
    {
        return $this->hasManyThrough('App\Models\Order', 'App\Models\Customer');
    }

    public function wallet()
    {
        return $this->hasOne('App\Models\Wallet', 'object_id');
    }

    public function getLinkAttribute()
    {

        $url = url('/mngrAdmin/corporates/' . $this->id);
        return "<a href=" . $url . " />" . $this->name . "</a>";
    }

    public function type()
    {
        return $this->belongsTo('App\Models\OrderType', 'order_type');
    }

    public function responsible_user()
    {
        return $this->belongsTo('App\Models\User', 'responsible_id');
    }

    public function government()
    {
        return $this->belongsTo('App\Models\Governorate', 'government_id');
    }

    public function store()
    {
        return $this->belongsTo('App\Models\Store', 'store_id');
    }

    public static function boot()
    {

        parent::boot();

        Corporate::updated(function ($model) {
            if (($model->is_active != $model->getOriginal('is_active')) && $model->is_active == 1 && !$model->wallet) {
                Wallet::insert([
                    'type' => 2,
                    'object_id' => $model->id,
                    'status' => 1
                ]);
            }
        });

        Corporate::created(function ($model) {
            if ($model->is_active == 1) {
                Wallet::insert([
                    'type' => 2,
                    'object_id' => $model->id,
                    'status' => 1
                ]);
            }
        });

    }

}

app/Http/Controllers/Backend/ActitivyLogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Activity_log;
use App\Models\Activity_log_type;
use Flash;

class ActitivyLogController extends Controller
{

    public function index(Request $request)
    {

        $activityLogs = Activity_log::orderBy('id', 'desc');
        $date = app('request')->input('date');
        $filter = app('request')->input('filter');

        if( isset($date) && $date != "") {
           $activityLogs = $activityLogs->whereDate('created_at','like',$date.'%');
        }

        if( isset($filter) && $filter !="" && $filter != -1 ) {
           $activityLogs = $activityLogs->where('activity_type' , $filter);
        }

        $activityLogs = $activityLogs->paginate(50);

          if ($request->ajax()) {
              return [
                  'view' => view('backend.activity_log.table', compact('activityLogs'))->render(),
              ];
          }

        $ActivityLogType = Activity_log_type::all();
        return view('backend.activity_log.index', compact('activityLogs', 'ActivityLogType'));
    }

    public function destroy($id)
    {
        $activityLog = Activity_log::findOrFail($id);
        $activityLog->delete();

        flash(__('backend.deleted_activityLog_successfully'))->error();

        return redirect()->back();
    }

}

app/Http/Controllers/Backend/Controller.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/backend/corporates/table.blade.php
<div class="row">
    <div class="col-md-12 col-xs-12 col-sm-12">
        @if($corporates->count())
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>{{__('backend.name')}}</th>
                    <th>{{__('backend.shipping_type')}}</th>
                    <th>{{__('backend.order_type')}}</th>
                    <th>{{__('backend.government')}}</th>
                    <th>{{__('backend.account_type')}}</th>
                    <th>{{__('backend.mobile_number')}}</th>
                    <th>{{__('backend.responsible')}}</th>
                    <th>{{__('backend.active')}}</th>
                    <th>{{__('backend.in_slider')}}</th>
                    <th>{{__('backend.created_at')}}</th>
                    <th>
                        <input type="button" class="btn btn-info btn-xs" id="toggle"
                               value="Select" onClick="do_this()"/>
                        <button type="button" id="pdf-submit"
                                class="btn btn-warning btn-pdf btn-xs ">{{__('backend.print')}}</button>
                    </th>
                    {{--                    <th class="text-right"></th>--}}
                </tr>
                </thead>
                <tbody>
                @foreach($corporates as $corporate)
                    <tr @if(permission('showCorporate')) class='clickable-row'
                        data-href="{{ route('mngrAdmin.corporates.show', $corporate->id) }}"
                        @endif @if($corporate->is_something_wrong) style='background: #9e8f9e; color: #fff' @endif>
                        <td>{{$corporate->id}}</td>
                        <td>{{$corporate->name}}</td>
                        <td>{{$corporate->type_of_shipping}}</td>
                        <td>
                            {{isset($corporate->type->name_en) ? $corporate->type->name_en : '-'}}
                        </td>
                        <td>
                            {{isset($corporate->government->name_en) ? $corporate->government->name_en : '-'}}
                        </td>
                        <td>{{$corporate->type_of_account}}</td>
                        <td>{{$corporate->mobile}}</td>
                        <td>{{isset($corporate->responsible_user->name) ? $corporate->responsible_user->name : '-'}}</td>
                        <td class="exclude-td">
                            <input data-id="{{$corporate->id}}" data-size="mini" class="toggle change_active"
                                   {{$corporate->is_active == 1 ? 'checked' : ''}} data-onstyle="success"
                                   type="checkbox" data-style="ios" data-on="Yes" data-off="No">

                        </td>

                        <td class="exclude-td">

                            <input data-id="{{$corporate->id}}" data-size="mini" class="toggle change_slider"
                                   {{$corporate->in_slider == 1 ? 'checked' : ''}} data-onstyle="success"
                                   type="checkbox" data-style="ios" data-on="Yes" data-off="No">

                        </td>

                        <td>{{$corporate->created_at}}</td>
                        <td class="exclude-td selectpdf" id="selectpdf">
                            <input type="checkbox" name="select[]" value="{{$corporate->id}}"
                                   class="selectOrder"
                                   data-value="{{$corporate->id}}"/>

                        </td>
                        {{--                        <td class="exclude-td">--}}
                        {{--                        @if(permission('showOrdersMember')) <!-- This Function Displays All The Buttons For All Peoples Have The Permission [Helpers.php] -->--}}
                        {{--                            <a class="btn btn-xs btn-default"--}}
                        {{--                               href="{{url('mngrAdmin/orders/showOrders') . '/2' . '/' . $corporate->id}}"><i--}}
                        {{--                                    class="glyphicon glyphicon-list"></i> {{__('backend.the_orders')}}</a>--}}
                        {{--                        @endif--}}

                        {{--                        --}}{{--                        @if(permission('showCorporate')) <!-- This Function Displays All The Buttons For All Peoples Have The Permission [Helpers.php] -->--}}
                        {{--                        --}}{{--                            <a class="btn btn-xs btn-primary"--}}
                        {{--                        --}}{{--                               href="{{ route('mngrAdmin.corporates.show', $corporate->id) }}"><i--}}
                        {{--                        --}}{{--                                    class="glyphicon glyphicon-eye-open"></i> {{__('backend.view')}}</a>--}}
                        {{--                        --}}{{--                        @endif--}}

                        {{--                        @if(permission('editCorporate')) <!-- This Function Displays All The Buttons For All Peoples Have The Permission [Helpers.php] -->--}}
                        {{--                            <a class="btn btn-xs btn-warning"--}}
                        {{--                               href="{{ route('mngrAdmin.corporates.edit', $corporate->id) }}"><i--}}
                        {{--                                    class="glyphicon glyphicon-edit"></i> {{__('backend.edit')}}</a>--}}
                        {{--                            @endif--}}

                        {{--                        </td>--}}
                    </tr>
                @endforeach
                </tbody>
            </table>

            {!! $corporates->appends($_GET)->links() !!}

        @else
            <h3 class="text-center alert alert-warning">{{__('backend.No_result_found')}}!</h3>
        @endif
    </div>
</div>