routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sms/{l}/{m}', 'FrontController@SendSMSCode');

Route::get('/test/{l}/{m}', 'FrontController@test');

Route::get('/landing', function () {
    return view('frontend.landing.index');
});

Route::get('/', 'FrontController@index')->name('home');
Route::get('/login', 'FrontController@get_login')->name('login');
Route::post('/login', 'FrontController@login')->name('post_login');
Route::get('/about', 'FrontController@about')->name('about');
Route::get('/services', 'FrontController@services')->name('service');
Route::get('/captain', 'FrontController@captain')->name('captain');
Route::get('/customer', 'FrontController@customer')->name('customer');
Route::get('/tracking', 'FrontController@tracking')->name('tracking');
Route::get('/register', 'FrontController@get_register')->name('register');
Route::post('/register', 'FrontController@register')->name('post_register');
Route::get('/contact', 'FrontController@contact')->name('contact');
Route::post('/contact', 'FrontController@contact_post')->name('contact_post');
Route::get('/terms', 'FrontController@terms')->name('terms');
Route::get('/forgotpassword', 'FrontController@get_forgotpassword')->name('forgotpassword');
Route::post('/forgotpassword', 'FrontController@forgotpassword')->name('forgotPassword');
Route::get('/active_account/{k}', 'FrontController@get_active_account')->name('active_account');
Route::post('/active_account', 'FrontController@active_account')->name('post_active_account');
Route::post('/forgotpasswordcode', 'FrontController@forgotpasswordcode')->name('forgotpasswordcode');
Route::post('/send_active_code', 'FrontController@send_active_code')->name('send_active_code');
Route::post('/resetpassword', 'FrontController@resetpassword')->name('resetpassword');
Route::post('/tracking', 'FrontController@search_tracking')->name('search_tracking');

Route::group(['prefix' => '/customer/account', 'as' => 'profile.', 'middleware' => 'customer'], function () {
    Route::get('/', 'FrontController@dashboard')->name('dashboard');
    Route::get('orders', 'FrontController@orders')->name('orders');
    Route::get('orders/{id}', 'FrontController@orderview')->name('orderview');
    Route::get('orders/{id}/edit', 'FrontController@order_edit_without_lang')->name('order_edit');
    Route::put('orders/{id}', 'FrontController@order_update')->name('order_update');
    Route::get('invoices/', 'FrontController@indexprofilewebsite');

    Route::get("reports/daily_report", "FrontController@profile_daily_report");
    Route::post("reports/daily_report", "Backend\ReportController@profile_daily_report");
    Route::post("orders/add_order_comment", "FrontController@addOrderComment");

    Route::get("invoices", "FrontController@indexInvoice")->name('invoices.index');
    Route::get("invoices/{id}", "FrontController@showInvoice")->name('invoices.show');
    Route::get("print/invoices/{id}", "FrontController@printInvoice");

    Route::get("refund_collections", "FrontController@indexRefund")->name('refund_collections.index');
    Route::any("print_refund", "Backend\ReportController@print_refund")->name("orders.print_refund");
    Route::any("refund_excel", "Backend\ReportController@refund_excel")->name("orders.refund_excel");

    Route::get('upload-excel', 'FrontController@getupdate');
    Route::post('upload-excel', 'FrontController@upload');
    Route::get('process-sheet/{id}', 'FrontController@process');
    Route::post("handle_sheet", "FrontController@handle_sheet");
    Route::post("export_sheet", "FrontController@export_sheet");
    Route::get('order-form', 'FrontController@order_form');
    Route::post('complete_collection/{id}', 'FrontController@complete_collection');
    Route::get('form-collections', 'FrontController@order_form_list')->name('collectionOrders');
    Route::any('form-collections/delete/{id}', 'FrontController@delete_collection')->name('collectionOrders.delete');
    Route::get('wallets', 'FrontController@profilewallet');
    Route::post('cancel_orders', 'FrontController@cancel_orders')->name('cancel_orders');
    Route::post('cancel_orders_request', 'FrontController@cancel_orders_request')->name('cancel_orders_request');
//    Route::get('wallets/', function () {
//        return view('frontend.profile.under_processing');
//    });
    Route::post('tmporders_create', 'FrontController@tmporders_create');
    #tmporders_update_view
    Route::get('tmporders_update_view/{key}', 'FrontController@tmporders_update_view');
    #tmporders_reset_view
    Route::get('tmporders_reset_view/{key}', 'FrontController@tmporders_reset_view');
    Route::get('/recall_if_dropped/{id}', 'FrontController@recall_if_dropped')->name('orders.recall_if_dropped');
    Route::get('logout', 'FrontController@logout');
    Route::get('changepassword', 'FrontController@get_changepassword');
    Route::post('changepassword', 'FrontController@changepassword');
    Route::get('notifications', 'FrontController@notifications');
    Route::get('notifications/delete', 'FrontController@delete_notification')->name('notifications.delete');

    Route::post('edit-profile', 'FrontController@edit_profile')->name('edit-profile');

    Route::get('get_cost/{key}/{receiver}', 'Backend\OrderController@get_cost_sender_receiver');

    Route::any("print_police", "Backend\ReportController@print_police");

    Route::get("customers/details/{id}", "CustomerController@details")->name('customers.details');
    Route::get("customers", "CustomerController@index")->name('customers.index');
    Route::get("customers/create", "CustomerController@create")->name('customers.create');
    Route::post("customers", "CustomerController@store")->name('customers.store');
    Route::get("customers/{id}", "CustomerController@show")->name('customers.show');
    Route::get("customers/{id}/edit", "CustomerController@customer_edit_without_lang")->name('customers.edit');
    Route::put("customers/{id}/update", "CustomerController@update")->name('customers.update');
    Route::delete("customers/{id}", "CustomerController@destroy")->name('customers.destroy');

    Route::get("tasks/cancel_pickup/{key}", "TaskOrderController@cancel_pickup");
    Route::get("tasks/details/{id}", "TaskOrderController@details")->name('tasks.details');
    Route::get("tasks", "TaskOrderController@index")->name('tasks.index');
    Route::get("tasks/create", "TaskOrderController@create")->name('tasks.create');
    Route::post("tasks", "TaskOrderController@store")->name('tasks.store');
    Route::get("tasks/{id}", "TaskOrderController@show")->name('tasks.show');
    Route::get("tasks/{id}/edit", "TaskOrderController@customer_edit_without_lang")->name('tasks.edit');
    Route::put("tasks/{id}/update", "TaskOrderController@update")->name('tasks.update');
    Route::delete("tasks/{id}", "TaskOrderController@destroy")->name('tasks.destroy');
});


Route::group(['prefix' => '{locale}', 'where' => ['locale' => '[a-zA-Z]{2}'], 'middleware' => 'setlocale'], function () {
    Route::get('/', 'FrontController@index')->name('home');
    Route::get('/login', 'FrontController@get_login')->name('login');
    Route::post('/login', 'FrontController@login')->name('post_login');
    Route::get('/about', 'FrontController@about')->name('about');
    Route::get('/services', 'FrontController@services')->name('service');
    Route::get('/captain', 'FrontController@captain')->name('captain');
    Route::get('/customer', 'FrontController@customer')->name('customer');
    Route::get('/tracking', 'FrontController@tracking')->name('tracking');
    Route::get('/register', 'FrontController@get_register')->name('register');
    Route::post('/register', 'FrontController@register')->name('post_register');
    Route::get('/contact', 'FrontController@contact')->name('contact');
    Route::post('/contact', 'FrontController@contact_post')->name('contact_post');
    Route::get('/terms', 'FrontController@terms')->name('terms');
    Route::get('/forgotpassword', 'FrontController@get_forgotpassword')->name('forgotpassword');
    Route::post('/forgotpassword', 'FrontController@forgotpassword')->name('forgotPassword');
    Route::get('/active_account/{k}', 'FrontController@get_active_account')->name('active_account');
    Route::post('/active_account', 'FrontController@active_account')->name('post_active_account');
    Route::post('/forgotpasswordcode', 'FrontController@forgotpasswordcode')->name('forgotpasswordcode');
    Route::post('/send_active_code', 'FrontController@send_active_code')->name('send_active_code');
    Route::post('/resetpassword', 'FrontController@resetpassword')->name('resetpassword');
    Route::post('/tracking', 'FrontController@search_tracking')->name('search_tracking');


    Route::group(['prefix' => '/customer/account', 'as' => 'profile.', 'middleware' => 'customer'], function () {
        Route::get("customers/details/{id}", "CustomerController@details")->name('customers.details');
        Route::get("customers", "CustomerController@index")->name('customers.index');
        Route::get("customers/create", "CustomerController@create")->name('customers.create');
        Route::post("customers", "CustomerController@store")->name('customers.store');
        Route::get("customers/{id}", "CustomerController@show")->name('customers.show');
        Route::get("customers/{id}/edit", "CustomerController@edit")->name('customers.edit');
        Route::put("customers/{id}/update", "CustomerController@update")->name('customers.update');
        Route::delete("customers/{id}", "CustomerController@destroy")->name('customers.destroy');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class Customer extends Authenticatable
{

    protected $hidden = ['password', 'created_at', 'updated_at', 'provider', 'provider_id', 'type', 'is_block', 'sms_code'];
    protected $fillable = ['name', 'email', 'password', 'mobile', 'sms_code'];

    //Customer Relationships ...
    public function devices()
    {
        return $this->hasMany('App\Models\Device', 'object_id', 'id')
            ->where('object_type', 1);
    }

    public function CustomerDevice()
    {
        return $this->hasMany('App\Models\Device');
    }

    public function orders()
    {
        return $this->hasMany('App\Models\Order');
    }

    public function task_days()
    {
        return $this->hasMany('App\Models\CustomerTaskDay');
    }

    public function pendingOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 0);
    }

    public function acceptedOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 1);
    }

    public function receivedOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 2);
    }

    public function deliveredOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 3);
    }

    public function cancelledOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 4);
    }

    public function recalledOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 5);
    }

    public function droppedOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 7);
    }

    public function rejectedOrders()
    {
        return $this->hasMany('App\Models\Order')->where('orders.status', 8);
    }

    public function prices()
    {
        return $this->hasMany('App\Models\CustomerPrice');
    }

    public function Corporate()
    {
        return $this->belongsTo('App\Models\Corporate');
    }

    public function governorate()
    {
        return $this->belongsTo('App\Models\Governorate', 'government_id');
    }

    public function city()
    {
        return $this->belongsTo('App\Models\City', 'city_id');
    }

    public function collection_orders()
    {
        return $this->hasOne('App\Models\CollectionOrder', 'customer_id');
    }

    public function store()
    {
        return $this->belongsTo('App\Models\Store', 'store_id');
    }

    public function getIsSomethingWrongAttribute()
    {

        $result = false;

        if (!$this->store_id) {
            $result = true;
        } elseif (!$this->government_id) {
            $result = true;
        }

        return $result;
    }

    //Customer Attributes ...
    public function getBlockSpanAttribute($value)
    {
        /*
        * is_block = 0 :: Not Blocked
        * is_block = 1 :: Blocked
        */
        if ($this->is_block == 1) {
            $value = "<span class='badge badge-pill label-danger'>" . __('backend.blocked') . "</span>";
        } else {
            $value = "<span class='badge badge-pill label-info'>" . __('backend.not_blocked') . "</span>";
        }
        return $value;
    }

    public function getBlockTxtAttribute($value)
    {
        /*
        * is_block = 0 :: Not Blocked
        * is_block = 1 :: Blocked
        */
        if ($this->is_block == 1) {
            $value = __('backend.not_blocked');
        } else {
            $value = __('backend.blocked');
        }
        return $value;
    }

    public function getActiveSpanAttribute($value)
    {
        /*
        * is_active = 0 :: Not Active
        * is_active = 1 :: Active
        */
        if ($this->is_active == 1) {
            $value = "<span class='badge badge-pill label-success'>" . __('backend.active') . "</span>";
        } else {
            $value = "<span class='badge badge-pill label-danger'>" . __('backend.not_activated') . "</span>";
        }
        return $value;
    }

    public function getMobileVerifySpanAttribute($value)
    {
        if ($this->is_verify_mobile != 1) {
            $value = "<span class='badge badge-pill label-danger'>" . __('backend.not_verified') . "</i></span>";
        } else {
            $value = "<span class='badge badge-pill label-success'>" . __('backend.verified') . "</span>";
        }
        return $value;
    }

    public function getStatusTxtAttribute($value)
    {
        /*
        * is_active = 0 :: Not Active
        * is_active = 1 :: Active
        */
        if ($this->is_active != 1) {
            $value = __('backend.active');
        } else {
            $value = __('backend.not_activated');
        }
        return $value;
    }

    /*type_span*/
    public function getTypeSpanAttribute()
    {
        if ($this->role_id == 3) {
            $value = "<span class='badge badge-pill label-info'>Individual Account</span>";
        } else {
            $value = "<span class='badge badge-pill label-warning'>Corporate Account</span>";
        }
        return $value;
    }


    public function getImageAttribute($value)
    {
        if ($value != "") {
            if (\File::exists(public_path("/api_uploades/client/profile/" . $value))) {
                $value = asset("/api_uploades/client/profile/" . $value);
            } else {
                $value = "";
            }
        } else {
            $value = "";
        }
        return $value;
    }

    #hash password
    public function setPasswordAttribute($pass)
    {
        $this->attributes['password'] = bcrypt($pass);
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [
            'type' => 'customer'
        ];
    }
}

resources/views/frontend/profile/customers/index.blade.php
@extends('frontend.profile.layouts.app')

@section('title') @lang('website.Orders') @endsection
@section('css')
    <title>{{__('backend.corporates')}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
    <style>
        input[type=checkbox], input[type=radio] {
            width: 18px;
            height: 18px;
        }

        .printdata {
            cursor: pointer;
        }

        .selectAll-button {
            color: #fff;
            background-color: #5bc0de;
            border-color: #46b8da;

        }

        .submit-button {
            color: #fff;
            background-color: #0376d9;
        }

        .cancel-button {
            background-color: #ff5900;
            border-color: #ed5301;
        }

        .button-padding {
            padding: 5px 14px;
        }
    </style>
@endsection
@section('content')
    <div class="flash-message"></div>
    <!-- Modal For Cancel Orders-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="exampleModalLabel">{{__('website.add_cancel_comment')}}</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label for="reason">{{__('website.comment')}}</label>
                            <textarea class="form-control" id="reason" name="reason" rows="3"></textarea>
                        </div>
                        <div class="col-6"></div>
                        <div class="col-md-12">
                            <button type="button" class="btn btn-secondary pull-right" data-dismiss="modal"
                                    style="margin-left: 15px;">Close
                            </button>
                            <button type="submit" class="btn btn-primary pull-right cancel-order submit-button"
                                    id="cancel-order" data-value="dropped"
                            >{{__('website.submit')}}</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="">
                <div class="table-responsive m-t-40">
                    <h1 class="title" style="margin-bottom: 10px">
                        @lang('backend.customers')
                        <div class="button-box">
                            <a href="{{ app()->getLocale() == 'en' ? url('/en/customer/account/customers/create') : url('/customer/account/customers/create') }}" class="btn btn-primary" style="">
                                @lang('backend.add_customer')</a>
                        </div>
                    </h1>
                    <form
                        action="{{ app()->getLocale() == 'en' ? url('/en/customer/account/customers') : url('/customer/account/customers') }}"
                        method="get">
                        <input type="hidden" name="type" value="{{ app('request')->input('type')}}">
                        <div class="row" style="margin-bottom:15px;" id="customers">
                            <div class="col-md-12" style="padding: 0">
                                <div class="group-control col-md-3 col-sm-3">
                                    <input type="text" class="form-control" id="search-field" name="search"
                                           value="{{ app('request')->input('search')}}"
                                           placeholder="{{__('backend.search')}} ">
                                </div>

{{--                                <div class="group-control col-md-3 col-sm-3">--}}
{{--                                    <select id="r_government_id" name="r_government_id" class="form-control">--}}
{{--                                        <option value=""--}}
{{--                                                data-display="Select">{{__('backend.Receiver_Government')}}</option>--}}
{{--                                        @if(! empty($app_governments))--}}
{{--                                            @foreach($app_governments as $government)--}}
{{--                                                <option value="{{$government->id}}"--}}
{{--                                                        @if(app('request')->input('r_government_id') == $government->id) selected @endif>--}}
{{--                                                    {{$government->name_en}}--}}
{{--                                                </option>--}}

{{--                                            @endforeach--}}
{{--                                        @endif--}}

{{--                                    </select>--}}
{{--                                </div>--}}

                                <div class="group-control col-md-2 col-sm-2">
                                    <button type="submit" style="padding: 8px;"
                                            class="btn btn-primary btn-block"> {{__('backend.filter')}} </button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <form method="post" id="myform" action="{{ url('/customer/account/print_police') }}"
                          target="_blank">
                        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
                        <table id="example23" class="display nowrap table table-hover table-striped table-bordered"
                               cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{{__('backend.name')}}</th>
                                <th>{{__('backend.mobile')}}</th>
                                <th>{{__('backend.created_at')}}</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($customers as $customer)
                                <tr>
                                    <td>{{$customer->id}}</td>
                                    <td>{{$customer->name}}</td>
                                    <td>{{$customer->mobile}}</td>

                                    <td>{{ $customer->created_at }}</td>

                                    <td>

                                    {{--                @if(permission('showCustomer')) <!-- This Function Displays All The Buttons For All Peoples Have The Permission [Helpers.php] -->--}}
                                    {{--                  <a class="btn btn-xs btn-primary" href="{{ route('mngrAdmin.customers.show', $customer->id) }}"><i class="glyphicon glyphicon-eye-open"></i> {{__('backend.view')}}</a>--}}
                                    {{--                @endif--}}

                                        <a class="btn btn-xs btn-warning"
                                           href="{{ route('profile.customers.edit', ['id' => $customer->id, 'locale' => ( app()->getLocale() == 'en' ? 'en' : 'ar')]) }}">
                                            <i class="icon-edit"></i> {{__('backend.edit')}}</a>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </form>
                    @if (! empty($customers) )
                        {!! $customers->appends($_GET)->links() !!}
                    @endif
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

    <script>

        // Select All Orders function For Cancel
        function do_this() {
            var checkboxes = document.getElementsByName('select[]');
            var button = document.getElementById('toggle');

            if (button.value === '{{__('website.select_all')}}') {
                for (var i in checkboxes) {
                    checkboxes[i].checked = true;
                }
                button.value = '{{__('website.deselect_all')}}'
            } else {
                for (var i in checkboxes) {
                    checkboxes[i].checked = false;
                }
                button.value = '{{__('website.select_all')}}';
            }
        }

        $('.cancel-order').on('click', function () {
            $("#exampleModal").modal("hide");
            let selected_order_ids = [];
            let checkboxes = document.getElementsByName('select[]');
            var _token = $('#_token');
            var order_type = $(this).attr('data-value');
            console.log('orders type', order_type);

            for (let i in checkboxes) {
                if (checkboxes[i].checked === true) {
                    selected_order_ids.push(checkboxes[i].value);
                }
            }
            if (selected_order_ids.length > 0) {
                if (order_type === 'pending') {
                    $.ajax({
                        url: '{{ route('profile.cancel_orders') }}',
                        type: 'post',
                        data: {
                            _token: "{{ csrf_token() }}",
                            'orders_to_cancel': selected_order_ids,
                        },
                        success: function (data) {
                            location.reload();
                            var successAlert = '<div class="alert alert-success alert-block text-center">' +
                                '            <button type="button" class="close" data-dismiss="alert">×</button>' +
                                '            <strong>{{__('website.cancelled_orders_success')}}</strong></div>';
                            $('div.flash-message').html(successAlert);

                        },
                        error: function (data) {

                        }

                    });
                } else if (order_type === 'dropped') {
                    let reason = $('#reason').val();
                    console.log('drooppppep', reason);
                    $.ajax({
                        url: '{{ route('profile.cancel_orders_request') }}',
                        type: 'post',
                        data: {
                            _token: "{{ csrf_token() }}",
                            'orders_ids_to_cancel': selected_order_ids,
                            'reason': reason,
                        },
                        success: function (data) {
                            location.reload();
                            var successAlert = '<div class="alert alert-success alert-block text-center">' +
                                '            <button type="button" class="close" data-dismiss="alert">×</button>' +
                                '            <strong>{{__('website.cancelled_orders_success')}}</strong></div>';
                            $('div.flash-message').html(successAlert);

                        },
                        error: function (data) {
                            let warning = ' <button type="button" class="close" data-dismiss="alert">×</button>' +
                                '            <strong>{{__('website.')}}</strong>';
                            $('div.flash-message').html(warning);

                        }

                    });
                }


            } else {
                $.confirm({
                    title: '',
                    theme: 'modern',
                    content: '<div class="jconfirm-title-c jconfirm-hand">' +
                        '<span class="jconfirm-icon-c"><i class="fa fa-frown-o  text-danger"></i></span>' +
                        '<span class="jconfirm-title">{{__('website.cancel_order')}}</span></div>' +
                        '<div style="font-weight:bold;"><p>{{__("website.must_choose_order_to_cancel")}}</p></div>',
                    type: 'red',
                });
            }


        });


    </script>
@endsection