routes/web.php
        Route::get("tasks/create", "TaskOrderController@create")->name('tasks.create');
        Route::post("tasks", "TaskOrderController@store")->name('tasks.store');
        Route::get("tasks/{id}", "TaskOrderController@show")->name('tasks.show');
        Route::get("tasks/{id}/edit", "TaskOrderController@edit")->name('tasks.edit');
        Route::put("tasks/{id}/update", "TaskOrderController@update")->name('tasks.update');
        Route::delete("tasks/{id}", "TaskOrderController@destroy")->name('tasks.destroy');

        Route::get('/', 'FrontController@dashboard')->name('dashboard');
        Route::get('orders', 'FrontController@orders')->name('orders');
        Route::get('orders/{id}', 'FrontController@orderview')->name('orderview');
        Route::get('orders/{id}/edit', 'FrontController@order_edit')->name('order_edit');
        Route::get("invoices", "FrontController@indexInvoice")->name('invoices.index');
        Route::get("invoices/{id}", "FrontController@showInvoice")->name('invoices.show');
        Route::get("print/invoices/{id}", "FrontController@printInvoice");

        Route::get("refund_collections", "FrontController@indexRefund")->name('refund_collections.index');
        Route::any("print_refund", "Backend\ReportController@print_refund")->name("orders.print_refund");
        Route::any("refund_excel", "Backend\ReportController@refund_excel")->name("orders.refund_excel");

        Route::get('upload-excel', 'FrontController@getupdate');
        Route::post('upload-excel', 'FrontController@upload');
        Route::get('process-sheet/{id}', 'FrontController@process');
        Route::post("handle_sheet", "FrontController@handle_sheet");
        Route::post("export_sheet", "FrontController@export_sheet");

        Route::get('order-form', 'FrontController@order_form');
        Route::post('complete_collection/{id}', 'FrontController@complete_collection');
        Route::get('form-collections', 'FrontController@order_form_list')->name('collectionOrders');
        Route::any('form-collections/delete/{id}', 'FrontController@delete_collection')->name('collectionOrders.delete');
        Route::get('wallets', 'FrontController@profilewallet');
//        Route::get('wallets/', function () {
//            return view('frontend.profile.under_processing');
//        });

        Route::any("print_police", "Backend\ReportController@print_police");

        Route::post('tmporders_create', 'FrontController@tmporders_create');

        #tmporders_update_view
        Route::get('tmporders_update_view/{key}', 'FrontController@tmporders_update_view');
        #tmporders_reset_view
        Route::get('tmporders_reset_view/{key}', 'FrontController@tmporders_reset_view');
        Route::get('logout', 'FrontController@logout');
        Route::get('changepassword', 'FrontController@get_changepassword');
        Route::post('changepassword', 'FrontController@changepassword');

        Route::get('notifications', 'FrontController@notifications');
        Route::get('notifications/delete', 'FrontController@delete_notification')->name('notifications.delete');;

        Route::post('edit-profile', 'FrontController@edit_profile')->name('edit-profile');


    });

});


Route::get('lang/{locale}', function ($locale) {
    Session::put('lang', $locale);
    return redirect()->back();
});

Route::get("check-email-agent", "Backend\AgentController@check_agent_email");
Route::get("check-mobile-agent", "Backend\AgentController@check_agent_mobile");
Route::get("check-phone-agent", "Backend\AgentController@check_agent_phone");

Route::get("check-email-corporate", "Backend\CorprateController@check_corporate_email");
Route::get("check-mobile-corporate", "Backend\CorprateController@check_corporate_mobile");

Route::get("check-email-customer", "Backend\CustomerController@check_customer_email");
Route::get("check-mobile-customer", "Backend\CustomerController@check_customer_mobile");

// By Mahmoud
Route::get("get_cities/{key}", "Backend\CityController@get_cities");

/*-*-*-*-*-*-*-*-*--*--*---** Agent Panel URL *---*-*--*-*-*-*-*-*-*-*-*-*-**/
Route::group(['prefix' => 'mngrAgent', 'as' => 'mngrAgent.', 'namespace' => 'Backend'], function () {

    Config::set('auth.defines.guard', 'agent');

    Route::post('/login', 'UserController@authenticate_agent');

    Route::get('/', function () {
        Config::set('auth.defines.guard', 'agent');
        return redirect('/mngrAgent/login');
    });
    Route::get('/login', function () {
        Config::set('auth.defines.guard', 'agent');
        if (Auth::guard('agent')->user()) {
            return redirect('/mngrAgent/dashboard');
        } else {
            return view('agent.login');
        }
    });


    Route::group(['middleware' => 'agent'], function () {

        Config::set('auth.defines.guard', 'agent');
        Route::resource("drivers", "DriverController", ['only' => ['index', 'show', 'create', 'store']]);
        Route::get('all_orders', 'OrderController@orders_agent_index')->name('mngrAgent/all_orders');
        Route::get('invoices/{type}', 'InvoiceController@invoicee')->name('invoices');
        Route::get('invoices/show/{id}', 'InvoiceController@shwoInvoiceid')->name('shwoInvoiceid');
        Route::get('invoices/driveres/show/{id}', 'InvoiceController@mydrivereshow')->name('mydrivereshow');
        Route::get('Pilot_Orders', 'OrderController@Pilot_Orders')->name('Pilot_Orders');
        Route::get('showpilotdriver/{driver_id}/{order_id}/{delv_id}/{acc_id}', 'OrderController@showpilotdriver')->name('showpilotdriver');
        Route::post('Pilot_update', 'OrderController@pilotupdata')->name('pilotupdata');
        #ask_review_order
        Route::get('/ask_review_order/{key}', 'OrderViewController@ask_review_order');

        Route::get('/dashboard', 'AgentController@dashboard');
        Route::get('/403', function () {
            Config::set('auth.defines.guard', 'agent');
            return view('agent.403');
        });
        Route::get('/404', function () {
            Config::set('auth.defines.guard', 'agent');
            return view('agent.404');
        });
        Route::post('/logout', 'UserController@logout');

        Route::resource("shipment_tool_orders", "ShipmentToolOrderController");
        #list_suggested
        Route::get("list_suggested", "OrderController@list_suggested");
        Route::resource("trucks", "TruckController", ['only' => ['index', 'show', 'create', 'store']]);
        Route::resource("agent_invoices", "AgentInvoiceController", ['only' => ['index', 'show']]);
        Route::resource("agents", "AgentController");

        Route::get("orders/ShowOrders/{type}/{id}", "OrderController@ShowOrders")->name("orders.showOrders");

        Route::resource("orders", "OrderController");
        #orders_agent_pending
        Route::get("pending_orders", "OrderController@orders_agent_pending");
        Route::get("waiting_orders", "OrderController@orders_agent_waiting");

        Route::get("list_by_drivers/{key}", "OrderController@list_by_drivers");
        Route::get("new_shippeng_field", "ShipmentToolOrderController@new_shippeng_field");
        Route::get('/track_drivers/{key}', 'DriverController@track_drivers');
        Route::get('/profile', 'AgentController@get_agent_profile');
        Route::get('/edit-profile', 'AgentController@get_agent_edit_profile');
        Route::put('/edit-profile', 'AgentController@post_agent_edit_profile');
        Route::post('/del/{id}', 'DriverController@del');
        Route::get("trucks/driversTrucks/{id}", "TruckController@DriverVehicle")->name('trucks.DriverVehicle');
        Route::post("users/addfirebaseToken", "UserController@firebaseToken")->name("users.addfirebaseToken");
        Route::resource("users", "UserController");

        Route::post('send_to_other_driver', 'OrderController@send_to_other_driver');

    });
});
/* *-*-*-*-*-*-*-*-*-*-*-*-* ADMIN PANEL URL -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
Route::group(['prefix' => 'mngrAdmin', 'as' => 'mngrAdmin.', 'namespace' => 'Backend'], function () {
    Config::set('auth.defines.guard', 'admin');
// Admin
    Route::post('/login', 'UserController@authenticate');

    Route::get('/', function () {
        return redirect('/mngrAdmin/login');
    });

    Route::get('/login', function () {
        if (Auth::guard('admin')->user()) {
            return redirect('/mngrAdmin/dashboard');
        }
        return view('backend.login');
    });

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/403', function () {
            return view('backend.403');
        });
        Route::get('/404', function () {
            return view('backend.404');
        });
        Route::post('/logout', 'UserController@logout');
        Route::get('/track_drivers/{key}', 'DriverController@track_drivers');

        // Route::resource("shipment_tools" 		,"ShipmentToolController");
        Route::get("shipment_tools", "ShipmentToolController@index")->name('shipment_tools.index')->middleware('Permition:shipmentTools');
        Route::get("shipment_tools/create", "ShipmentToolController@create")->name('shipment_tools.create')->middleware('Permition:addShipmentTools');
        Route::post("shipment_tools", "ShipmentToolController@store")->name('shipment_tools.store')->middleware('Permition:addShipmentTools');
        Route::get("shipment_tools/{id}", "ShipmentToolController@show")->name('shipment_tools.show')->middleware('Permition:showShipmentTools');
        Route::get("shipment_tools/{id}/edit", "ShipmentToolController@edit")->name('shipment_tools.edit')->middleware('Permition:editShipmentTools');
        Route::put("shipment_tools/{id}/update", "ShipmentToolController@update")->name('shipment_tools.update')->middleware('Permition:editShipmentTools');
        Route::delete("shipment_tools/{id}", "ShipmentToolController@destroy")->name('shipment_tools.destroy')->middleware('Permition:deleteShipmentTools');

app/Models/Agent.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{

    public function getAgentData(){
        return $this->hasOne('App\Models\User','agent_id');
    }

    public function getEmailAttribute()
    {
        $user = User::where('agent_id',$this->id)->first();
        if (! empty($user)) {
          return $user->email;
        }
        return "";
      }

    public function getStatusSpanAttribute($value)
    {
        /*
        * status = 0 :: Not Active
        * status = 1 :: Active
        */
        if($this->status == 0){
            $value="<span class='badge badge-pill label-danger'>".__('backend.not_activated')."</span>";
        }else if($this->status == 1){
            $value="<span class='badge badge-pill label-success'>".__('backend.active')."</span>";
        }else{
          $value = "";
        }
        return $value;
    }

  	public function getStatusTxtAttribute($value) {
        /*
        * status = 0 :: Not Active
        * status = 1 :: Active
        */
        if($this->status == 0 || $this->status != 1) {
            $value= __('backend.active');
        } elseif($this->status == 1) {
            $value= __('backend.not_activated');
        } else {
          $value = "";
        }
        return $value;
    }

    public function wallet()
    {
        return $this->hasOne('App\Models\Wallet','object_id');
    }

}

app/Models/User.php
<?php

namespace App\Models;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Role_admin;

class User extends Authenticatable
{
    use Notifiable,EntrustUserTrait;


    protected $fillable = [
        'name', 'email', 'password'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getIsWarehouseUserAttribute()
    {
        if($this->roleAdmin->is_warehouse_role){
            return true;
        }

        return false;
    }

	public function getBlockSpanAttribute($value)
  {
      /*
      * is_active = 0 :: Not Active
      * is_active = 1 :: Active
      */
      if($this->is_active != 1){
          $value="<span class='badge badge-pill label-danger'>".__('backend.blocked')."</span>";
      }else{
          $value="<span class='badge badge-pill label-success'>".__('backend.not_blocked')."</span>";
      }
      return $value;
  }

  public function getBlocksSpanAttribute($value)
    {
        /*
        * is_active = 0 :: Not Active
        * is_active = 1 :: Active
        */
        if($this->is_active != 1){
            $value="<span class='badge badge-pill label-danger'><i class='fa fa-times' aria-hidden='true'></i></span>";
        }else{
            $value="<span class='badge badge-pill label-success'><i class='fa fa-check' aria-hidden='true'></i></span>";
        }
        return $value;
    }

	 public function getBlockTxtAttribute($value)
    {
        /*
        * is_active = 0 :: Not Active
        * is_active = 1 :: Active
        */
        if($this->is_active != 1){
            $value = __('backend.not_blocked');
        }else{
            $value = __('backend.blocked');
        }
        return $value;
    }

    public function getImageAttribute($value)
    {
        if($value != ""){
            $value=url("/")."/public/backend/images/".$value;
        }else{
          $value = "";
        }
        return $value;
    }

    public function agent() {
        return $this->belongsTo('App\Models\Agent','agent_id');
    }
    public function roleAdmin(){
        return $this->belongsTo('App\Models\Role_admin', 'role_admin_id');
    }

}

resources/views/agent/403.blade.php
@extends('agent.layouts.app')

@section('content')
<div class="col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1 main">

    <section class="content-header">
      <h1>
        403 Error Page
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{URL::asset('/mngrAgent/dashboard')}}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        
        <li class="active">403 Error</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="error-page">
        <h2 class="headline text-yellow"> 403</h2>

        <div class="error-content">
          <h3><i class="fa fa-warning text-yellow"></i> OPPs! Something Error!</h3>

          <p>
            You are Not Allwoed to Access this page
          </p>


        </div>
        <!-- /.error-content -->
      </div>
      <!-- /.error-page -->
    </section>
    <!-- /.content -->

  
  </div>
@endsection

resources/views/agent/404.blade.php
@extends('agent.layouts.app')

@section('content')
<div class="col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1 main">

    <section class="content-header">
      <h1>
        404 Error Page
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{URL::asset('/mngrAgent/dashboard')}}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        
        <li class="active">404 Error</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="error-page">
        <h2 class="headline text-yellow"> 404</h2>

        <div class="error-content">
          <h3><i class="fa fa-warning text-yellow"></i> OPPs! Something Error!</h3>

          <p>
            Not Found
          </p>


        </div>
        <!-- /.error-content -->
      </div>
      <!-- /.error-page -->
    </section>
    <!-- /.content -->

  
  </div>
@endsection

resources/views/agent/dashboard.blade.php
@extends('agent.layouts.app')
@section('css')
<link rel="stylesheet" type="text/css" href="{{URL::asset('/assets/css/dashboard.css')}}">
<link href="{{URL::asset('/public/backend/css/style.css')}}" rel="stylesheet" type="text/css" media="all"/>
@endsection
@section('content')
<style>
.tab td{
  font-size: 15px;
  font-weight: bold;
  color: #334a5e;
  text-transform: capitalize;
}
.w3-message h5, .w3ls-touch h5 , .page-header {
  color: #566877;
  margin: 0;
  letter-spacing: 2px;
  font-size: 4rem;
  font-weight: bold;
}
</style>
<div class="panel panel-headline">
        <div class="profile-pic wthree">
            @if (! empty($user->image))
            <a data-toggle="lightbox" href="#demoLightbox" > <img
                        style="height: 100px;width:100px;"
                        src="{{ $user->image }}"></a>
			<div id="demoLightbox" class="lightbox fade"  tabindex="-1" role="dialog" aria-hidden="true">
   			 <div class='lightbox-dialog'>
       			 <div class='lightbox-content'>
     		       <img src="{{ $user->image }}">
        		</div>
    		</div>
  		</div>
            @endif
        <!-- </div> -->
        <div class="w3-message">
            <h5 class="page-header">About Me</h5>
            <table class="table table-condensed table-striped">
              <tr style="color:#297cc4;" class="tab">
                 <td>
                    name
                </td>
                 <td>
                    mobile
                </td>
                <td>
                     email
                </td>
              </tr>
              <tr style="color: #566877;">
                  <td >
                      {{$agent->name}}
                  </td>
                   <td>
                      {{! empty($agent) ? $agent->mobile : ''}}
                  </td>
                   <td>
                    {{ ! empty($agent) ?  $agent->email : '' }}
                  </td>
              </tr>
                <tr style="color:#297cc4;" class="tab">
                     <td>
                        Phone
                    </td>

                     <td>
                        Fax
                    </td>
                      <td>
                        Commercial Record Number
                    </td>

                </tr>
                <tr>

                    <td>
                        {{$agent->phone}}
                    </td>
                     <td>
                        {{$agent->fax}}
                    </td>
                     <td>
                        {{$agent->commercial_record_number}}
                    </td>
                </tr>

                <tr style="color:#297cc4;" class="tab">

                    <td>
                        Address
                    </td>

                    <td>
                        Deal Date
                    </td>
                    <td>
                        Profit Rate
                    </td>

                </tr>
                <tr>

                     <td>
                        {{$agent->address}}
                    </td>
                     <td>
                        {{$agent->deal_date}}
                    </td>

                    <td>
                        {{$agent->profit_rate}}
                    </td>

                </tr>

            </table>

        </div>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header" style="font-weight:bold;">Statistics</h1>
        </div>
    </div><!--/.row-->

    <div class="panel panel-container">
    <div class="row">
    <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-havan panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-truck color-havan"></em>
                <div class="large">{{! empty($trucks) ? $trucks : '0'}}</div>
                <div class="text-muted">No. All Vehicles</div>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-blue panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-user-o  color-green"></em>
                <div class="large">{{! empty($drivers) ? $drivers : '0'}}</div>
                <div class="text-muted">No. All Drivers</div>
            </div>
        </div>
    </div>

    <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-dark panel-widget ">
            <div class="row no-padding"><em class="fa fa-xl fa-times  color-red"></em>
                <div class="large">{{! empty($not_actived_drivers) ? $not_actived_drivers : '0'}}</div>
                <div class="text-muted">No. Not Verified Drivers</div>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-dark panel-widget ">
            <div class="row no-padding"><em class="fa fa-xl fa-check-circle  color-online"></em>
                <div class="large">{{! empty($actived_drivers) ? $actived_drivers : '0'}}</div>
                <div class="text-muted">No. Verified Drivers</div>
            </div>
        </div>
    </div>


     <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-pink panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-compass color-pink"></em>
                <div class="large">{{! empty($orders) ? $orders : '0'}}</div>
                <div class="text-muted">No. All Orders</div>
            </div>
        </div>
    </div>

    <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-green panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-circle color-online"></em>
                <div class="large">{{! empty($onlines) ? $onlines : '0'}}</div>
                <div class="text-muted">No. Online Drivers</div>
            </div>
        </div>
    </div>

     <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-red panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-circle-o color-red"></em>
                <div class="large">{{! empty($offlines) ? $offlines : '0'}}</div>
                <div class="text-muted">No. Offline Drivers</div>
            </div>
        </div>
    </div>

     <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
        <div class="panel panel-pink panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-star color-pink"></em>
                <div class="large">{{! empty($busy) ? $busy : '0'}}</div>
                <div class="text-muted">No.Busy Drivers</div>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>

@endsection
@section('scripts')
<script src="{{URL::asset('/public/js/firebaseAgent.js')}}"></script>
@endsection

resources/views/agent/edit-profile.blade.php
@extends('agent.layouts.app')
@section('css')

@endsection
@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-edit"></i>  Edit Agents #{{$agent->id}}</h3>
    </div>
@endsection

@section('content')


    <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">

            <form action="{{ URL::asset('mngrAgent/edit-profile') }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group col-md-6 col-sm-6 @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $agent->name : old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group col-md-6 col-sm-6 @if($errors->has('mobile')) has-error @endif">
                       <label for="mobile-field">Mobile</label>
                    <input type="text" id="mobile-field" name="mobile" class="form-control" value="{{ is_null(old("mobile")) ? $agent->mobile : old("mobile") }}"/>
                       @if($errors->has("mobile"))
                        <span class="help-block">{{ $errors->first("mobile") }}</span>
                       @endif
                    </div>
                      <div class="form-group col-md-6 col-sm-6 @if($errors->has('email')) has-error @endif">
                       <label for="email-field">E-mail</label>
                    <input type="text" id="email-field" name="email" class="form-control" value="{{ is_null(old("email")) ? $agent->email : old("email") }}"/>
                       @if($errors->has("email"))
                        <span class="help-block">{{ $errors->first("email") }}</span>
                       @endif
                    </div>
                    <div class="form-group col-md-6 col-sm-6 @if($errors->has('phone')) has-error @endif">
                       <label for="phone-field">Phone</label>
                    <input type="text" id="phone-field" name="phone" class="form-control" value="{{ is_null(old("phone")) ? $agent->phone : old("phone") }}"/>
                       @if($errors->has("phone"))
                        <span class="help-block">{{ $errors->first("phone") }}</span>
                       @endif
                    </div>
                    <div class="form-group col-md-6 col-sm-6 @if($errors->has('fax')) has-error @endif">
                       <label for="fax-field">Fax</label>
                    <input type="text" id="fax-field" name="fax" class="form-control" value="{{ is_null(old("fax")) ? $agent->fax : old("fax") }}"/>
                       @if($errors->has("fax"))
                        <span class="help-block">{{ $errors->first("fax") }}</span>
                       @endif
                    </div>
                  
                     <div class="form-group col-md-6 col-sm-6 @if($errors->has('profit_rate')) has-error @endif">
                       <label for="profit_rate-field">Profit Rate</label>
                    <input type="number" min="0" id="profit_rate-field" name="profit_rate" class="form-control" value="{{ is_null(old("profit_rate")) ? $agent->profit_rate : old("profit_rate") }}"/>
                       @if($errors->has("profit_rate"))
                        <span class="help-block">{{ $errors->first("profit_rate") }}</span>
                       @endif
                    </div>
                    <div class="form-group col-md-6 col-sm-6 @if($errors->has('commercial_record_number')) has-error @endif">
                       <label for="commercial_record_number-field">Commercial Record Number</label>
                    <input type="text" id="commercial_record_number-field" name="commercial_record_number" class="form-control" value="{{ is_null(old("commercial_record_number")) ? $agent->commercial_record_number : old("commercial_record_number") }}"/>
                       @if($errors->has("commercial_record_number"))
                        <span class="help-block">{{ $errors->first("commercial_record_number") }}</span>
                       @endif
                    </div>
                    <div class="form-group col-md-6 col-sm-6 @if($errors->has('deal_date')) has-error @endif">
                       <label for="deal_date-field">Deal Date</label>
                       <div class='input-group date ' id="datepicker">
                       

                    <input type="text" id="deal_date-field" name="deal_date" class="form-control" value="{{ is_null(old("deal_date")) ? $agent->deal_date : old("deal_date") }}"/>

                     <div class="input-group-addon">
                          <i class="fa fa-calendar"></i>
                        </div>
                        </div>
                       @if($errors->has("deal_date"))
                        <span class="help-block">{{ $errors->first("deal_date") }}</span>
                       @endif
                    </div>
                   
                    <div class="form-group col-md-6 col-sm-6 @if($errors->has('latitude')) has-error @endif">
                       <label for="latitude-field">Latitude</label>
                    <input type="text" id="latitude-field" name="latitude" class="form-control" value="{{ is_null(old("latitude")) ? $agent->latitude : old("latitude") }}"/>
                       @if($errors->has("latitude"))
                        <span class="help-block">{{ $errors->first("latitude") }}</span>
                       @endif
                    </div>
                    <div class="form-group col-md-6 col-sm-6 @if($errors->has('longitude')) has-error @endif">
                       <label for="longitude-field">Longitude</label>
                    <input type="text" id="longitude-field" name="longitude" class="form-control" value="{{ is_null(old("longitude")) ? $agent->longitude : old("longitude") }}"/>
                       @if($errors->has("longitude"))
                        <span class="help-block">{{ $errors->first("longitude") }}</span>
                       @endif
                    </div>

                     <div class="form-group col-md-6 col-sm-6 @if($errors->has('password')) has-error @endif">
                       <label for="password-field">Password</label>
                    <input type="password" id="password-field" name="password" class="form-control" value="{{ old("password") }}"/>
                       @if($errors->has("password"))
                        <span class="help-block">{{ $errors->first("password") }}</span>
                       @endif
                    </div>


                     <div class="form-group col-md-6 col-sm-6 @if($errors->has('confirm_password')) has-error @endif">
                       <label for="confirm_password-field">Confirm Password</label>
                    <input type="password" id="confirm_password-field" name="confirm_password" class="form-control" value="{{ old("confirm_password") }}"/>
                       @if($errors->has("confirm_password"))
                        <span class="help-block">{{ $errors->first("confirm_password") }}</span>
                       @endif
                    </div>

                      <div class="form-group col-md-6 col-sm-6 @if($errors->has('address')) has-error @endif">
                       <label for="address-field">Address</label>
                    <textarea class="form-control" id="address-field" rows="4" name="address">{{ is_null(old("address")) ? $agent->address : old("address") }}</textarea>
                       @if($errors->has("address"))
                        <span class="help-block">{{ $errors->first("address") }}</span>
                       @endif
                    </div>

                    <div hidden class="form-group col-md-6 col-sm-6 @if($errors->has('status')) has-error @endif">
                       <label for="status-field" style="display: block;">Status</label>
                   
                         <input type="hidden" name="status" value="{{$agent->status}}" />
                       @if($errors->has("status"))
                        <span class="help-block">{{ $errors->first("status") }}</span>
                       @endif
                    </div>
                    
                <div class="well well-sm col-md-12 col-xs-12 col-sm-12">
                    <button type="submit" class="btn btn-primary">Save</button>
                    
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  
@endsection