routes/web.php
        Route::get("tasks/create", "TaskOrderController@create")->name('tasks.create');
        Route::post("tasks", "TaskOrderController@store")->name('tasks.store');
        Route::get("tasks/{id}", "TaskOrderController@show")->name('tasks.show');
        Route::get("tasks/{id}/edit", "TaskOrderController@edit")->name('tasks.edit');
        Route::put("tasks/{id}/update", "TaskOrderController@update")->name('tasks.update');
        Route::delete("tasks/{id}", "TaskOrderController@destroy")->name('tasks.destroy');

        Route::get('/', 'FrontController@dashboard')->name('dashboard');
        Route::get('orders', 'FrontController@orders')->name('orders');
        Route::get('orders/{id}', 'FrontController@orderview')->name('orderview');
        Route::get('orders/{id}/edit', 'FrontController@order_edit')->name('order_edit');
        Route::get("invoices", "FrontController@indexInvoice")->name('invoices.index');
        Route::get("invoices/{id}", "FrontController@showInvoice")->name('invoices.show');
        Route::get("print/invoices/{id}", "FrontController@printInvoice");

        Route::get("refund_collections", "FrontController@indexRefund")->name('refund_collections.index');
        Route::any("print_refund", "Backend\ReportController@print_refund")->name("orders.print_refund");
        Route::any("refund_excel", "Backend\ReportController@refund_excel")->name("orders.refund_excel");

        Route::get('upload-excel', 'FrontController@getupdate');
        Route::post('upload-excel', 'FrontController@upload');
        Route::get('process-sheet/{id}', 'FrontController@process');
        Route::post("handle_sheet", "FrontController@handle_sheet");
        Route::post("export_sheet", "FrontController@export_sheet");

        Route::get('order-form', 'FrontController@order_form');
        Route::post('complete_collection/{id}', 'FrontController@complete_collection');
        Route::get('form-collections', 'FrontController@order_form_list')->name('collectionOrders');
        Route::any('form-collections/delete/{id}', 'FrontController@delete_collection')->name('collectionOrders.delete');
        Route::get('wallets', 'FrontController@profilewallet');
//        Route::get('wallets/', function () {
//            return view('frontend.profile.under_processing');
//        });

        Route::any("print_police", "Backend\ReportController@print_police");

        Route::post('tmporders_create', 'FrontController@tmporders_create');

        #tmporders_update_view
        Route::get('tmporders_update_view/{key}', 'FrontController@tmporders_update_view');
        #tmporders_reset_view
        Route::get('tmporders_reset_view/{key}', 'FrontController@tmporders_reset_view');
        Route::get('logout', 'FrontController@logout');
        Route::get('changepassword', 'FrontController@get_changepassword');
        Route::post('changepassword', 'FrontController@changepassword');

        Route::get('notifications', 'FrontController@notifications');
        Route::get('notifications/delete', 'FrontController@delete_notification')->name('notifications.delete');;

        Route::post('edit-profile', 'FrontController@edit_profile')->name('edit-profile');


    });

});


Route::get('lang/{locale}', function ($locale) {
    Session::put('lang', $locale);
    return redirect()->back();
});

Route::get("check-email-agent", "Backend\AgentController@check_agent_email");
Route::get("check-mobile-agent", "Backend\AgentController@check_agent_mobile");
Route::get("check-phone-agent", "Backend\AgentController@check_agent_phone");

Route::get("check-email-corporate", "Backend\CorprateController@check_corporate_email");
Route::get("check-mobile-corporate", "Backend\CorprateController@check_corporate_mobile");

Route::get("check-email-customer", "Backend\CustomerController@check_customer_email");
Route::get("check-mobile-customer", "Backend\CustomerController@check_customer_mobile");

// By Mahmoud
Route::get("get_cities/{key}", "Backend\CityController@get_cities");

/*-*-*-*-*-*-*-*-*--*--*---** Agent Panel URL *---*-*--*-*-*-*-*-*-*-*-*-*-**/
Route::group(['prefix' => 'mngrAgent', 'as' => 'mngrAgent.', 'namespace' => 'Backend'], function () {

    Config::set('auth.defines.guard', 'agent');

    Route::post('/login', 'UserController@authenticate_agent');

    Route::get('/', function () {
        Config::set('auth.defines.guard', 'agent');
        return redirect('/mngrAgent/login');
    });
    Route::get('/login', function () {
        Config::set('auth.defines.guard', 'agent');
        if (Auth::guard('agent')->user()) {
            return redirect('/mngrAgent/dashboard');
        } else {
            return view('agent.login');
        }
    });


    Route::group(['middleware' => 'agent'], function () {

        Config::set('auth.defines.guard', 'agent');
        Route::resource("drivers", "DriverController", ['only' => ['index', 'show', 'create', 'store']]);
        Route::get('all_orders', 'OrderController@orders_agent_index')->name('mngrAgent/all_orders');
        Route::get('invoices/{type}', 'InvoiceController@invoicee')->name('invoices');
        Route::get('invoices/show/{id}', 'InvoiceController@shwoInvoiceid')->name('shwoInvoiceid');
        Route::get('invoices/driveres/show/{id}', 'InvoiceController@mydrivereshow')->name('mydrivereshow');
        Route::get('Pilot_Orders', 'OrderController@Pilot_Orders')->name('Pilot_Orders');
        Route::get('showpilotdriver/{driver_id}/{order_id}/{delv_id}/{acc_id}', 'OrderController@showpilotdriver')->name('showpilotdriver');
        Route::post('Pilot_update', 'OrderController@pilotupdata')->name('pilotupdata');
        #ask_review_order
        Route::get('/ask_review_order/{key}', 'OrderViewController@ask_review_order');

        Route::get('/dashboard', 'AgentController@dashboard');
        Route::get('/403', function () {
            Config::set('auth.defines.guard', 'agent');
            return view('agent.403');
        });
        Route::get('/404', function () {
            Config::set('auth.defines.guard', 'agent');
            return view('agent.404');
        });
        Route::post('/logout', 'UserController@logout');

        Route::resource("shipment_tool_orders", "ShipmentToolOrderController");
        #list_suggested
        Route::get("list_suggested", "OrderController@list_suggested");
        Route::resource("trucks", "TruckController", ['only' => ['index', 'show', 'create', 'store']]);
        Route::resource("agent_invoices", "AgentInvoiceController", ['only' => ['index', 'show']]);
        Route::resource("agents", "AgentController");

        Route::get("orders/ShowOrders/{type}/{id}", "OrderController@ShowOrders")->name("orders.showOrders");

        Route::resource("orders", "OrderController");
        #orders_agent_pending
        Route::get("pending_orders", "OrderController@orders_agent_pending");
        Route::get("waiting_orders", "OrderController@orders_agent_waiting");

        Route::get("list_by_drivers/{key}", "OrderController@list_by_drivers");
        Route::get("new_shippeng_field", "ShipmentToolOrderController@new_shippeng_field");
        Route::get('/track_drivers/{key}', 'DriverController@track_drivers');
        Route::get('/profile', 'AgentController@get_agent_profile');
        Route::get('/edit-profile', 'AgentController@get_agent_edit_profile');
        Route::put('/edit-profile', 'AgentController@post_agent_edit_profile');
        Route::post('/del/{id}', 'DriverController@del');
        Route::get("trucks/driversTrucks/{id}", "TruckController@DriverVehicle")->name('trucks.DriverVehicle');
        Route::post("users/addfirebaseToken", "UserController@firebaseToken")->name("users.addfirebaseToken");
        Route::resource("users", "UserController");

        Route::post('send_to_other_driver', 'OrderController@send_to_other_driver');

    });
});
/* *-*-*-*-*-*-*-*-*-*-*-*-* ADMIN PANEL URL -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
Route::group(['prefix' => 'mngrAdmin', 'as' => 'mngrAdmin.', 'namespace' => 'Backend'], function () {
    Config::set('auth.defines.guard', 'admin');
// Admin
    Route::post('/login', 'UserController@authenticate');

    Route::get('/', function () {
        return redirect('/mngrAdmin/login');
    });

    Route::get('/login', function () {
        if (Auth::guard('admin')->user()) {
            return redirect('/mngrAdmin/dashboard');
        }
        return view('backend.login');
    });

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/403', function () {
            return view('backend.403');
        });
        Route::get('/404', function () {
            return view('backend.404');
        });
        Route::post('/logout', 'UserController@logout');
        Route::get('/track_drivers/{key}', 'DriverController@track_drivers');

        // Route::resource("shipment_tools" 		,"ShipmentToolController");
        Route::get("shipment_tools", "ShipmentToolController@index")->name('shipment_tools.index')->middleware('Permition:shipmentTools');
        Route::get("shipment_tools/create", "ShipmentToolController@create")->name('shipment_tools.create')->middleware('Permition:addShipmentTools');
        Route::post("shipment_tools", "ShipmentToolController@store")->name('shipment_tools.store')->middleware('Permition:addShipmentTools');
        Route::get("shipment_tools/{id}", "ShipmentToolController@show")->name('shipment_tools.show')->middleware('Permition:showShipmentTools');
        Route::get("shipment_tools/{id}/edit", "ShipmentToolController@edit")->name('shipment_tools.edit')->middleware('Permition:editShipmentTools');
        Route::put("shipment_tools/{id}/update", "ShipmentToolController@update")->name('shipment_tools.update')->middleware('Permition:editShipmentTools');
        Route::delete("shipment_tools/{id}", "ShipmentToolController@destroy")->name('shipment_tools.destroy')->middleware('Permition:deleteShipmentTools');

app/Models/Agent.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{

    public function getAgentData(){
        return $this->hasOne('App\Models\User','agent_id');
    }

    public function getEmailAttribute()
    {
        $user = User::where('agent_id',$this->id)->first();
        if (! empty($user)) {
          return $user->email;
        }
        return "";
      }

    public function getStatusSpanAttribute($value)
    {
        /*
        * status = 0 :: Not Active
        * status = 1 :: Active
        */
        if($this->status == 0){
            $value="<span class='badge badge-pill label-danger'>".__('backend.not_activated')."</span>";
        }else if($this->status == 1){
            $value="<span class='badge badge-pill label-success'>".__('backend.active')."</span>";
        }else{
          $value = "";
        }
        return $value;
    }

  	public function getStatusTxtAttribute($value) {
        /*
        * status = 0 :: Not Active
        * status = 1 :: Active
        */
        if($this->status == 0 || $this->status != 1) {
            $value= __('backend.active');
        } elseif($this->status == 1) {
            $value= __('backend.not_activated');
        } else {
          $value = "";
        }
        return $value;
    }

    public function wallet()
    {
        return $this->hasOne('App\Models\Wallet','object_id');
    }

}

app/Models/ShipmentToolOrder.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ShipmentToolOrder extends Model
{
    public function getNoItemsAttribute() {
    	$items = ShipmentOrderItem::where('shipment_order_id',$this->id)->count();
    	return $items;
    }

    public function items()	{
        return $this->hasMany('App\Models\ShipmentOrderItem','shipment_order_id');
    }

	  public function getStatusSpanAttribute() {
      if($this->status == 1){
          $value="<span class='badge badge-pill label-warning'>".__('backend.processing')."</span>";
      }else if($this->status == 2){
          $value="<span class='badge badge-pill label-success'>".__('backend.delivered')."</span>";
      }else{
        $value="<span class='badge badge-pill label-black'>".__('backend.pending')."</span>";
      }
      return $value;
    }

   public function ShipmentTool() {
      return $this->belongsToMany('App\Models\ShipmentTool', 'shipment_order_items', 'shipment_order_id', 'tool_id');
    }

	  public function agent() {
        return $this->belongsTo('App\Models\Agent','object_id');
    }
    public function customer() {
        return $this->belongsTo('App\Models\Customer','object_id');
    }
}

app/Models/index.blade.php
@extends('layouts.app')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Settings
            <a class="btn btn-success pull-right" href="{{ route('settings.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($settings->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>KEY</th>
                        <th>VALUE</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($settings as $setting)
                            <tr>
                                <td>{{$setting->id}}</td>
                                <td>{{$setting->key}}</td>
                    <td>{{$setting->value}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('settings.show', $setting->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('settings.edit', $setting->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('settings.destroy', $setting->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $settings->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/agent/shipment_tool_orders/create.blade.php
@extends('agent.layouts.app')
@section('css')

@endsection
@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-plus"></i> Create Shipment Tool Orders </h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">

            <form action="{{ route('mngrAgent.shipment_tool_orders.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="hidden" name="status" value="0">
                <input type="hidden" name="object_id" value="{{Auth::guard('agent')->user()->agent_id}}">
                    <div id="fields">
                    <div class="col-sm-12 col-md-12"  style="margin-top: 10px;">
                      <div class="col-sm-5 col-md-5">
                        <input required  type="number"  name="quantity[]" class="form-control" placeholder="Quantity"  />
                      </div>

                      <div class="form-group col-md-6 col-sm-6 @if($errors->has('items')) has-error @endif">
                           <select id="items-field" name="items[]" id="items" class="form-control">
                                @foreach($shipment_tools as $item)
                                    <option value="{{$item->id}}" {{ old("items") == $item->id ? 'selected' : '' }}
                                    >{{$item->name_en}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="input-group">
                          <span class="input-group-btn">
                              <input type="button" id="add-field" value="+" class="btn btn-success add-more">
                          </span>
                      </div>

                    </div>

                  </div>
                    <div class="col-sm-12 col-md-12" style="margin-bottom: 15px;">
                      <label for="notes-field">Address</label>
                      <input type="text" name="address" class="form-control" placeholder="address" required />
                    </div>

                    <div class="form-group col-md-12 col-sm-12 @if($errors->has('notes')) has-error @endif">
                       <label for="notes-field">Notes</label>
                    <textarea class="form-control" id="notes-field" rows="4" name="notes">{{ old("notes") }}</textarea>
                       @if($errors->has("notes"))
                        <span class="help-block">{{ $errors->first("notes") }}</span>
                       @endif
                    </div>

                <div class="well well-sm col-md-12 col-sm-12 col-xs-12">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('mngrAgent.shipment_tool_orders.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script type="text/javascript">
    $(function(){
      $("body").on("click", ".remove", function () {
        $(this).closest(".remove-field").remove();

      });

      $(".add-more").on('click',function(){
        $.ajax({
            url: "{{url('/mngrAgent/new_shippeng_field/')}}" ,
            type: 'get',

            success: function (data) {
                $('#fields').append(data.view);

            },
            error: function (data) {
                console.log('Error:', data);
            }
        });



      });
    });
  </script>
@endsection

resources/views/agent/shipment_tool_orders/edit.blade.php
@extends('agent.layouts.app')
@section('css')

@endsection
@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-edit"></i>  Edit ShipmentToolOrders #{{$shipment_tool_order->id}}</h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">

            <form action="{{ route('mngrAgent.shipment_tool_orders.update', $shipment_tool_order->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="hidden" name="status" value="{{$shipment_tool_order->status}}">
                <input type="hidden" name="agent_id" value="{{Auth::guard('agent')->user()->agent_id}}">
              
                   
                  <div id="fields">
                    
                    @if( ! empty($shipment_tool_order->items) && count($shipment_tool_order->items) >0)

                    @php
                      $i = 0;
                    @endphp
                      @foreach($shipment_tool_order->items as $item)
                    <div class="col-sm-12 col-md-12"  style="margin-top: 10px;"> 

                      <div class="col-sm-5 col-md-5">
                        <input required  type="number"  name="quantity[]" class="form-control" placeholder="Quantity" value="{{$item->quantity}}"  />
                      </div>

                      <div class="form-group col-md-6 col-sm-6 @if($errors->has('items')) has-error @endif">           
                           <select id="items-field" name="items[]" id="items" class="form-control">
                                
                                @if(! empty($shipment_tools))
                                    @foreach($shipment_tools as $item)
                                        <option value="{{$item->id}}" {{ old("items") == $item->id || $item->tool_id == $item->id ? 'selected' : '' }}
                                        >{{$item->title}}</option>

                                    @endforeach

                                @endif
                            </select>
                           
                        </div>

                        @if($i == 0)
                        <div class="input-group">

                          <span class="input-group-btn">
                              <input type="button" id="add-field" value="+" class="btn btn-success add-more">
                          </span>
                      </div>

                      @else

                      <div class="input-group">

                        <span class="input-group-btn">
                            <input type="button" id="remove-field" value="-" class="btn btn-danger remove">
                        </span>
                    </div>
                      @endif
                    </div>

                    @php
                      $i ++ ;
                    @endphp
                      @endforeach
                    @else

                    <div id="fields">
                    <div class="col-sm-12 col-md-12"  style="margin-top: 10px;"> 

                      <div class="col-sm-5 col-md-5">
                        <input required  type="number"  name="quantity[]" class="form-control" placeholder="Quantity"  />
                      </div>

                      <div class="form-group col-md-6 col-sm-6 @if($errors->has('items')) has-error @endif">           
                           <select id="items-field" name="items[]" id="items" class="form-control">
                                
                                @if(! empty($shipment_tools))
                                    @foreach($shipment_tools as $item)
                                        <option value="{{$item->id}}" {{ old("items") == $item->id ? 'selected' : '' }}
                                        >{{$item->title}}</option>

                                    @endforeach

                                @endif
                            </select>
                           
                        </div>

                        <div class="input-group">

                          <span class="input-group-btn">
                              <input type="button" id="add-field" value="+" class="btn btn-success add-more">
                          </span>
                      </div>

                    </div>

                  </div>
                    @endif
                    </div>


                     <div class="form-group col-md-12 col-sm-12 @if($errors->has('notes')) has-error @endif">
                       <label for="notes-field">Notes</label>
                    <textarea class="form-control" id="notes-field" rows="4" name="notes">{{ is_null(old("notes")) ? $shipment_tool_order->notes : old("notes") }}</textarea>
                       @if($errors->has("notes"))
                        <span class="help-block">{{ $errors->first("notes") }}</span>
                       @endif
                    </div>
                <div class="well well-sm col-md-12 col-xs-12 col-sm-12">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('mngrAgent.shipment_tool_orders.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
    $(function(){
      $("body").on("click", ".remove", function () {
        $(this).closest(".remove-field").remove();

      });

      $(".add-more").on('click',function(){
        $.ajax({
            url: "{{url('/mngrAgent/new_shippeng_field/')}}" ,
            type: 'get',

            success: function (data) {
                $('#fields').append(data.view);

            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
        


      });
    });
  </script>
@endsection

resources/views/agent/shipment_tool_orders/fields.blade.php
<div class="col-sm-12 col-md-12 remove-field"  style="margin-top: 10px;">

	<div class="col-sm-5 col-md-5">
		<input required id="quantity-field" type="number" name="quantity[]" class="form-control" placeholder="{{__('backend.quantity')}}"  />
	</div>

	<div class="form-group col-md-6 col-sm-6 @if($errors->has('items')) has-error @endif">
       <select id="items-field" name="items[]" class="form-control">
            @if(! empty($shipment_tools))
                @foreach($shipment_tools as $item)
                    <option value="{{$item->id}}" {{ old("items") == $item->id ? 'selected' : '' }}>
												@if(session()->has('lang') == 'ar')
													{{$item->name_ar}}
												@else
												{{$item->name_en}}
												@endif
										 </option>
                @endforeach
            @endif
        </select>
    </div>

  	<div class="input-group">
    	<span class="input-group-btn">
        	<input type="button" id="remove-field" value="-" class="btn btn-danger remove">
    	</span>
	</div>

</div>

resources/views/agent/shipment_tool_orders/index.blade.php
@extends('agent.layouts.app')

@section('header')
    <div class="page-header clearfix">
        <h3>
            <i class="glyphicon glyphicon-align-justify"></i> ShipmentToolOrders
            <a class="btn btn-success pull-right" href="{{ route('mngrAgent.shipment_tool_orders.create') }}"><i class="glyphicon glyphicon-plus"></i> New Request Tool</a>
        </h3>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">
            @if($shipment_tool_orders->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Status</th>
                            <th>created_at</th>
                            <th class="text-right"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($shipment_tool_orders as $shipment_tool_order)
                            <tr>
                                <td>{{$shipment_tool_order->shipitemordes_id}}</td>
                                <td>
                                  @if($shipment_tool_order->order_status == 0 )
                                      <span class='badge badge-pill badge-black'>Pending</span>
                                      @else
                                      <span class='badge badge-pill badge-success'>done</span>
                                    @endif
                                </td>
                                <td>{{$shipment_tool_order->created_at}}</td>
                                <td class="text-right">
                                  <a class="btn btn-xs btn-primary" href="{{ route('mngrAgent.shipment_tool_orders.show', $shipment_tool_order->shipitemordes_id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center alert alert-warning">No Result Found !</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/agent/shipment_tool_orders/show.blade.php
@extends('agent.layouts.app')
@section('header')
<div class="page-header">
        <h3>Show #{{$id}}</h3>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">
			<h4>Items</h4>
             <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Material</th>
                            <th>price</th>
                            <th>Quantity</th>
                            <th>Total Price</th>
                            <th>status</th>
                            <th>notes</th>
                        </tr>
                    </thead>
                    <tbody>
                      @foreach ($shipment_tool_order as $order)
                        <tr>
                            <td>{{$order->shipitemordes_id}}</td>
                            <td>{{$order->name_en}}</td>
                            <td>{{$order->price}}</td>
                            <td>{{$order->quantity}}</td>
                            <td>{{ $order->quantity * $order->price}}</td>
                            <td>
                              @if($order->status == 0 )
                                  <span class='badge badge-pill badge-black'>Pending</span>
                                  @else
                                  <span class='badge badge-pill badge-success'>done</span>
                                @endif
                            </td>
                            <td>{{ $order->notes }}</td>
                        </tr>
                        @endforeach
                    </tbody>
        		</table>
    </div>
</div>

          <div class="row">
            <div class="col-md-12 col-xs-12 col-sm-12">
                <a class="btn btn-link pull-right" href="{{ route('mngrAgent.shipment_tool_orders.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
            </div>
        </div>
    </div>

@endsection